version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "install"
      - pip3 install git-remote-codecommit
      - export SAM_CLI_TELEMETRY=0
      - npm install -g cfn-include
      - pip3 install bandit
      - gem install cfn-nag
      - pip3 install cfn_flip
      - export BASEDIR=$CODEBUILD_SRC_DIR
  pre_build:
    commands:
      - export ScriptsDir=$(pwd)/scripts
      - export ConfigFilePath=$CODEBUILD_SRC_DIR/common/config/config.json
  build:
    commands:
      - cd  components/lambdas
      - bash scan.sh $CODEBUILD_SRC_DIR/suppression.txt
      - cd $CODEBUILD_SRC_DIR
      - cd components
      - bash scan.sh $CODEBUILD_SRC_DIR/suppression.txt
      - cd $CODEBUILD_SRC_DIR
      - |
        bash scan-service-catalog-product.sh \
        $CODEBUILD_SRC_DIR/three-stage-cross-account-pipeline/cross-account-codepipeline.yml
      
artifacts:
  files:
    - '**/*'
