Resources:
  CodePipelineSourceBucket:
    Type: AWS::S3::Bucket
    Metadata:
          cfn_nag:
              rules_to_suppress:
                - id: W51
                  reason: "S3 bucket should likely have a bucket policy (TODO: We need to define a bucket policy)"
                - id: W35
                  reason: "S3 Bucket should have access logging configured (TODO: Do we need access logging?)"
                - id: W41
                  reason: "S3 Bucket should have encryption option set (TODO: Do we need encryption)"


Outputs:
  CodePipelineSourceBucket:
    Value: !Ref CodePipelineSourceBucket
    Export:
      Name: x-acct-codepipeline-source-bucket