Transform: AWS::Serverless-2016-10-31
Description: > 
  Creates a CloudFormation Custom Resource that forces CloudFormation to wait for a number of seconds

Globals:
  Function:
    Runtime: python3.7
    Timeout: 180
    Handler: index.lambda_handler

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lmd-csr-sleep
      CodeUri: ./src

Outputs:
  LambdaFunctionArn:
    Description: "Custom Resource that forces CloudFormation to wait for a number of seconds"
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: CFNSleep