AWSTemplateFormatVersion: '2010-09-09'
Description: Cross Account CodePipeline Service Catalog Product
Transform: AWS::Serverless-2016-10-31

Parameters:
 DevOpsAccount:
    Type: String
    AllowedPattern: \d{12}
    Description: Enter the AWS Account ID of the external account that will assume this role.
 Application:
    Type: String
 Environment:
    Type: String

Resources:
  CodeBuildRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Sub "codebuild-${Application}-${Environment}-${AWS::Region}"
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSCodeDeployDeployerAccess
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: Allow
              Principal:
                AWS: !Sub "arn:aws:iam::${DevOpsAccount}:root"
              Action:
                - sts:AssumeRole
              Condition:
                StringLike:
                  "aws:PrincipalArn": !Sub "arn:aws:iam::${DevOpsAccount}:role/codebuild-*"
            -
              Effect: Allow
              Principal:
                Service:
                  - codebuild.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /
  CodeBuildPolicy:
    Metadata:
          cfn_nag:
              rules_to_suppress:
                - id: F4
                  reason: This policy needs to be able to create a Role for Lambdas with the needed policies.
                - id: W12
                  reason: This policy needs to be able to create a Role for Lambdas with the needed policies.
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub CodeBuildPolicy-${AWS::Region}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Effect: Allow
            Action: 
              - s3:*
            Resource: 
              - !Join 
                - ''
                - - "arn:aws:s3:::"
                  - !ImportValue CodeDeploySourceBucket
                  - "/*"
              - !Join 
                - ''
                - - "arn:aws:s3:::"
                  - !ImportValue CodeDeploySourceBucket
          - 
            Effect: Allow
            Action:
              - cloudformation:DescribeStacks
            Resource: "*"
              
      Roles:
        -
          !Ref CodeBuildRole
Outputs:
  CodeBuildRole:
    Description: Cross Account Code Build Role
    Value: !Ref CodeBuildRole